<?php

namespace Henzeb\Warmable\Tests\Stubs;

use Henzeb\Warmable\Warmable;
use Mockery;
use Psr\SimpleCache\CacheInterface;

class HeavyInjectedRequest extends Warmable
{
    public static ?string $callWarmable = null;

    protected function warmable(InjectedService $service): string
    {
        return $service->value;
    }

    protected function cache(): CacheInterface
    {
        return Mockery::mock(CacheInterface::class);
    }

    protected function executeWarmable(): mixed
    {
        return static::$callWarmable ?? parent::executeWarmable(); // TODO: Change the autogenerated stub
    }

    public function __destruct()
    {
        static::$callWarmable = null;
    }
}
